#!/usr/bin/env python3
"""
Verify that all AIGC assets have been generated by comparing
video_struct.yaml scene definitions against actual files on disk.

Checks:
- All AIGC scenes have origin_asset_path set and file exists
- Asset files are non-empty
- Optionally checks asset_path (upscaled) if upscale step was run

Usage:
    python verify_aigc_assets.py --video-struct /abs/path/video_struct.yaml
    python verify_aigc_assets.py --video-struct /abs/path/video_struct.yaml --check-upscaled

Exit codes: 0 = all assets present, 1 = missing assets.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL_ROOT))

from lib.yamlutil import load_yaml


def verify(struct: dict, check_upscaled: bool = False) -> tuple[list[str], list[str]]:
    """Return (errors, warnings)."""
    errors = []
    warnings = []

    stories = struct.get("stories", [])
    total_aigc = 0
    origin_missing = []
    upscaled_missing = []

    for story in stories:
        for narration in story.get("narration_list", []):
            for scene in narration.get("scene_list", []):
                if not scene.get("is_aigc_scene", False):
                    continue

                total_aigc += 1
                scene_id = scene.get("id", "?")

                # Check origin_asset_path
                origin_path = scene.get("origin_asset_path", "")
                if not origin_path:
                    origin_missing.append(f"{scene_id}: origin_asset_path is empty")
                elif not Path(origin_path).exists():
                    origin_missing.append(f"{scene_id}: file not found: {origin_path}")
                elif Path(origin_path).stat().st_size == 0:
                    origin_missing.append(f"{scene_id}: file is empty: {origin_path}")

                # Check upscaled asset_path
                if check_upscaled:
                    asset_path = scene.get("asset_path", "")
                    if not asset_path:
                        upscaled_missing.append(f"{scene_id}: asset_path is empty")
                    elif not Path(asset_path).exists():
                        upscaled_missing.append(f"{scene_id}: upscaled file not found: {asset_path}")
                    elif Path(asset_path).stat().st_size == 0:
                        upscaled_missing.append(f"{scene_id}: upscaled file is empty: {asset_path}")

    if origin_missing:
        errors.append(f"Missing origin assets ({len(origin_missing)}/{total_aigc}):")
        errors.extend(f"  - {m}" for m in origin_missing)

    if check_upscaled and upscaled_missing:
        errors.append(f"Missing upscaled assets ({len(upscaled_missing)}/{total_aigc}):")
        errors.extend(f"  - {m}" for m in upscaled_missing)

    if total_aigc == 0:
        warnings.append("No AIGC scenes found in video_struct.yaml")

    return errors, warnings


def main() -> None:
    parser = argparse.ArgumentParser(description="Verify AIGC asset files")
    parser.add_argument("--video-struct", required=True, help="Path to video_struct.yaml (absolute)")
    parser.add_argument("--check-upscaled", action="store_true", help="Also verify asset_path (upscaled)")
    args = parser.parse_args()

    from lib.net import require_abs
    require_abs(args.video_struct)

    struct = load_yaml(args.video_struct)
    errors, warnings = verify(struct, check_upscaled=args.check_upscaled)

    if errors:
        print(json.dumps({
            "status": "error",
            "msg": f"AIGC asset verification failed",
            "data": {"errors": errors, "warnings": warnings},
        }, ensure_ascii=False, indent=2))
        sys.exit(1)
    elif warnings:
        print(json.dumps({
            "status": "warning",
            "msg": f"AIGC assets verified with warnings",
            "data": {"warnings": warnings},
        }, ensure_ascii=False, indent=2))
        sys.exit(2)
    else:
        print(json.dumps({
            "status": "ok",
            "msg": "All AIGC assets verified",
            "data": {},
        }, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
