#!/usr/bin/env python3
"""Generate per-scene Remotion composition files.

For every scene in narration_script.yaml (chapters → scenes → shots), this
writes three files under `scenes/{scene}/`:

    scene.tsx        — the scene composition: TransitionSeries over shots,
                       audio-master clock compensation, scene narration audio,
                       scene subtitles, shot overlays. Imports components from
                       the shared remotion-video-template (never copied).
    entry.tsx        — Composition registration; calculateMetadata reads the
                       scene's timing.json for durationInFrames.
    composition.json — JSON mirror of the scene's shot designs, read at
                       runtime via staticFile.

Rendering is per scene (each scene → scenes/{scene}/scene.mp4); scenes are
then concatenated losslessly by merge_video.py. --public-dir stays the video
root, so scene files resolve via staticFile("scenes/{scene}/...") and the
assets manifest stays shared at staticFile("assets/manifest.json").

Timing: each scene's timing.json lists `shots` with frame budgets. The scene
composition scales shots proportionally so the rendered total equals
timing.total_frames exactly (TransitionSeries overlap compensation — mirrors
the math from remotion-video-template/src/Video.js).
"""
import argparse
import json
import os
import sys

import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)
DOC_ROOT = os.path.normpath(os.path.join(SKILL_DIR, "..", ".."))
sys.path.insert(0, SCRIPT_DIR)
import cli_envelope  # noqa: E402
import script_schema  # noqa: E402
import themes as themes_mod  # noqa: E402
import workspace  # noqa: E402


def _template_path(prefs):
    """Resolve the remotion-video-template location.

    Relative paths are resolved against the explainer-video-maker root
    (DOC_ROOT), matching the documented convention: the template sits at
    ../remotion-video-template next to the skill repo root. Absolute paths
    are used as-is.
    """
    rel = prefs.get("paths", {}).get("remotion_template", "../remotion-video-template")
    if os.path.isabs(rel):
        return os.path.normpath(rel)
    return os.path.normpath(os.path.join(DOC_ROOT, rel))


def _composition_id(prefs):
    orientation = prefs.get("project", {}).get("orientation", "horizontal")
    resolution = prefs.get("video", {}).get("resolution", "1080p")
    if orientation == "vertical":
        return "MainVideoVertical"
    if resolution == "4k":
        return "MainVideo4K"
    return "MainVideo"


def _composition_dims(prefs):
    orientation = prefs.get("project", {}).get("orientation", "horizontal")
    resolution = prefs.get("video", {}).get("resolution", "1080p")
    if orientation == "vertical":
        return (1080, 1920)
    if resolution == "4k":
        return (3840, 2160)
    return (1920, 1080)


def _default_props(prefs):
    theme = prefs.get("theme", {})
    return {
        "primaryColor": theme.get("primary_color", "#1a2a3a"),
        "backgroundColor": theme.get("background_color", "#0e1419"),
        "textColor": theme.get("text_color", "#e6e8eb"),
        "accentColor": theme.get("accent_color", "#d4b483"),
        "titleSize": 80,
        "subtitleSize": 40,
        "bodySize": 28,
        # Progress bar is off by default for per-scene rendering: each scene
        # would reset 0→100%, which reads oddly after concatenation. Enable
        # to show in-scene shot-segment progress.
        "showProgressBar": False,
        "progressBarHeight": 65,
        "progressFontSize": 19,
        "progressActiveColor": theme.get("primary_color", "#1a2a3a"),
        "bgmVolume": 0,  # BGM is mixed via FFmpeg after scene merge (Step 10)
        "enableAudio": True,
        # Subtitles are burned in per scene by default (scene-relative SRT).
        "enableSubtitles": True,
        "enableAnimations": True,
        "transitionType": theme.get("transition_type", "fade"),
        "transitionDuration": theme.get("transition_duration", 18),
        "scaleFactor": 2 if prefs.get("video", {}).get("resolution") == "4k" else 1,
        "orientation": prefs.get("project", {}).get("orientation", "horizontal"),
        "iconStyle": "lucide",
        "iconAnimation": "entrance",
    }


SCENE_TSX_TEMPLATE = r"""// AUTO-GENERATED by explainer-video-maker/scripts/compose_video.py
// Per-scene composition for scene "__SCENE_NAME__".
// Imports components from the shared remotion-video-template.
//
// Audio-master clock (scene level): TransitionSeries renders
// sum(shots) - (N-1)*overlap. Every shot is scaled proportionally so the
// rendered total equals the scene timing.total_frames (which comes from the
// real scene narration WAV length). Overlap math mirrors
// remotion-video-template/src/Video.js.
//
// Shot layering: source material (asset_id → AssetImage/AssetVideo or a
// primary component) + auxiliary layers: overlays[] (transparent webm via
// OverlayLayer), data[] (charts/stats), text[] (quotes/bullets/callouts).

import React from "react";
import {
  Audio, staticFile, AbsoluteFill, useCurrentFrame,
  delayRender, continueRender, cancelRender,
} from "remotion";

// NOTE: TransitionSeries/linearTiming come from the template barrel (which
// re-exports @remotion/transitions) — a bare package import would not resolve
// from this per-scene file's location outside the template's node_modules.
import {
  Scale4K, FullBleedLayout, PaddedLayout,
  useEntrance, getPresentation,
  TransitionSeries, linearTiming,
  Subtitles,
  AssetImage, AssetVideo, MediaSection, OverlayLayer,
  Timeline, FlowChart, DataBar, QuoteBlock,
  StatHighlight, SplitLayout, ComparisonCard,
  DiagramReveal, MetricsRow, StepProgress,
  IconCard, Icon, FeatureGrid,
  MovingGradient, FloatingShapes, GlowOrb,
} from "__TEMPLATE_PATH__/src/components/index.js";

const SCENE = "__SCENE_NAME__";

// ── Scene timing loader (self-contained; template useTiming is hardcoded
//    to the root timing.json, but scenes live at scenes/{scene}/timing.json) ──
const timingCache = new Map();
const timingPending = new Map();

const useSceneTiming = () => {
  const url = staticFile(`scenes/${SCENE}/timing.json`);
  const cached = timingCache.get(url) ?? null;
  const [timing, setTiming] = React.useState(cached);
  const [handle] = React.useState(() =>
    cached ? null : delayRender(`Loading scenes/${SCENE}/timing.json`),
  );
  React.useEffect(() => {
    if (cached) return;
    if (!timingPending.has(url)) {
      timingPending.set(
        url,
        fetch(url)
          .then((r) => r.json())
          .then((data) => {
            timingCache.set(url, data);
            return data;
          }),
      );
    }
    timingPending
      .get(url)
      .then((data) => {
        setTiming(data);
        if (handle !== null) continueRender(handle);
      })
      .catch((err) =>
        cancelRender(new Error(`Failed to load scene timing for ${SCENE}: ${err}`)),
      );
  }, [handle, cached, url]);

  if (!timing) {
    return { total_duration: 0, fps: 30, total_frames: 1, shots: [] };
  }
  return timing;
};

// ── Data-item renderer (chart / stats components) ──────────────────────────
const RenderDataItem = ({ item, props, delay }) => {
  switch (item.type) {
    case "stat":
      return <StatHighlight props={props}
        value={item.value || ""} unit={item.unit || ""}
        label={item.label || ""} description={item.description || ""} />;

    case "bar_chart":
      return (
        <div style={{ width: "100%" }}>
          {item.title && <h2 style={{
            fontSize: props.orientation === "vertical" ? 48 : 40, fontWeight: 700,
            color: props.primaryColor, textAlign: "center", marginBottom: 24,
          }}>{item.title}</h2>}
          <DataBar props={props} items={item.items || []} />
        </div>
      );

    case "metrics":
      return <MetricsRow props={props}
        title={item.title || ""} metrics={item.metrics || []} />;

    case "steps":
      return <StepProgress props={props}
        title={item.title || ""} steps={item.steps || []} />;

    case "flow":
      return (
        <div style={{ width: "100%" }}>
          {item.title && <h2 style={{
            fontSize: props.orientation === "vertical" ? 48 : 40, fontWeight: 700,
            color: props.primaryColor, textAlign: "center", marginBottom: 24,
          }}>{item.title}</h2>}
          <FlowChart props={props} steps={item.steps || []} />
        </div>
      );

    case "timeline":
      return (
        <div style={{ width: "100%" }}>
          {item.title && <h2 style={{
            fontSize: props.orientation === "vertical" ? 48 : 40, fontWeight: 700,
            color: props.primaryColor, textAlign: "center", marginBottom: 24,
          }}>{item.title}</h2>}
          <Timeline props={props} items={item.items || []} />
        </div>
      );

    case "comparison":
      return <ComparisonCard props={props}
        left={item.left || { title: "", items: [] }}
        right={item.right || { title: "", items: [] }} />;

    default:
      return null;
  }
};

// ── Text-item renderer (quotes / bullet points / callouts) ─────────────────
const RenderTextItem = ({ item, props, delay }) => {
  const v = props.orientation === "vertical";
  switch (item.type) {
    case "quote":
      return <QuoteBlock props={props}
        quote={item.quote || ""} attribution={item.attribution || ""} />;

    case "key_points":
      return (
        <div style={{ width: "100%", display: "flex", flexDirection: "column", gap: v ? 24 : 20 }}>
          {item.title && <h2 style={{
            fontSize: v ? 48 : 40, fontWeight: 700,
            color: props.primaryColor, textAlign: "center",
          }}>{item.title}</h2>}
          {item.items.map((kv, i) => (
            <IconCard key={i} props={props}
              icon={kv.icon} title={kv.title}
              description={kv.description} delay={delay + i * 4} />
          ))}
        </div>
      );

    case "callout":
      return <IconCard props={props}
        icon={item.icon || "info"} title={item.text || item.title || ""} delay={delay} />;

    case "diagram":
      return <DiagramReveal props={props}
        nodes={item.nodes || []} edges={item.edges || []}
        width={item.width} height={item.height} />;

    default:
      return null;
  }
};

// ── Shot component — composes material + auxiliary layers ──────────────────
const ShotComponent = ({ shot, props }) => {
  const { opacity, translateY, scale } = useEntrance(props.enableAnimations);
  const animStyle = {
    opacity,
    transform: `translateY(${translateY}px) scale(${scale})`,
  };
  const v = props.orientation === "vertical";
  const shotPadding = v ? "120px 60px 160px" : "60px 100px 120px";
  const visual = shot.visual || {};
  const component = shot.component || visual.component || "default";
  const vp = shot.props || visual.props || {};
  const assetId = shot.asset_id || visual.asset_id;
  const dataItems = shot.data || [];
  const textItems = shot.text || [];
  const overlays = shot.overlays || [];
  const gap = v ? 40 : 32;

  // ── Main material ─────────────────────────────────────────────────────
  let mainVisual;
  switch (component) {
    case "FullBleedLayout":
    case "hero":
      mainVisual = (
        <React.Fragment>
          {assetId ? (
            <AssetImage props={props} id={assetId} role="background" />
          ) : (
            <MovingGradient color1={props.primaryColor} color2={props.accentColor} />
          )}
          <div style={{
            display: "flex", flexDirection: "column",
            justifyContent: "center", alignItems: "center",
            textAlign: "center",
            minHeight: dataItems.length + textItems.length > 0 ? "auto" : "100%",
          }}>
            <h1 style={{
              fontSize: props.titleSize, fontWeight: 800,
              color: props.primaryColor, lineHeight: v ? 1.3 : 1.1,
            }}>{vp.title || shot.label || shot.name}</h1>
            {vp.subtitle && (
              <p style={{
                fontSize: props.subtitleSize, color: props.textColor,
                marginTop: v ? 32 : 20, opacity: 0.6, fontWeight: 500,
              }}>{vp.subtitle}</p>
            )}
          </div>
        </React.Fragment>
      );
      break;

    case "Timeline":
      mainVisual = (
        <React.Fragment>
          <Timeline props={props} items={vp.items || []} />
        </React.Fragment>
      );
      break;

    case "FlowChart":
      mainVisual = <FlowChart props={props} steps={vp.steps || []} />;
      break;

    case "DiagramReveal":
      mainVisual = <DiagramReveal props={props} nodes={vp.nodes || []} edges={vp.edges || []} />;
      break;

    case "DataBar":
      mainVisual = <DataBar props={props} items={vp.items || []} />;
      break;

    case "QuoteBlock":
      mainVisual = <QuoteBlock props={props} quote={vp.quote || ""} attribution={vp.attribution || ""} />;
      break;

    case "ComparisonCard":
      mainVisual = <ComparisonCard props={props}
        left={vp.left || { title: "", items: [] }}
        right={vp.right || { title: "", items: [] }} />;
      break;

    case "MediaSection":
    case "AssetImage":
      mainVisual = assetId ? (
        <AssetImage props={props} id={assetId} role="inline"
          caption={vp.caption} layout={vp.layout || "full"} />
      ) : (
        <p style={{ fontSize: 28, textAlign: "center", opacity: 0.5 }}>AssetImage shot requires an asset_id.</p>
      );
      break;

    case "AssetVideo":
      return assetId ? (
        <AbsoluteFill>
          <AssetVideo props={props} id={assetId} />
          {overlays.map((ov, i) => (
            <div key={"ov" + i} style={{
              position: "absolute", inset: 0, pointerEvents: "none", ...(ov.style || {}),
            }}>
              <OverlayLayer id={ov.asset_id} />
            </div>
          ))}
        </AbsoluteFill>
      ) : null;

    default:
      mainVisual = (
        <h2 style={{
          fontSize: v ? 72 : 80, fontWeight: 700,
          color: props.primaryColor, textAlign: "center",
        }}>{shot.label || shot.name}</h2>
      );
  }

  // ── Auxiliary layers: transparent overlays ────────────────────────────
  const overlayEls = overlays.map((ov, i) => (
    <div key={"ov" + i} style={{
      position: "absolute", inset: 0, pointerEvents: "none", ...(ov.style || {}),
    }}>
      <OverlayLayer id={ov.asset_id} />
    </div>
  ));

  // ── Container choice ───────────────────────────────────────────────────
  const isHero = component === "FullBleedLayout" || component === "hero";
  const content = (
    <div style={{
      display: "flex", flexDirection: "column",
      gap, width: "100%",
      maxWidth: isHero ? undefined : 1100,
      margin: isHero ? undefined : "0 auto",
      ...animStyle,
    }}>
      {mainVisual}
      {dataItems.map((item, i) => (
        <RenderDataItem key={"d" + i} item={item} props={props} delay={i * 4} />
      ))}
      {textItems.map((item, i) => (
        <RenderTextItem key={"t" + i} item={item} props={props} delay={(dataItems.length + i) * 4} />
      ))}
    </div>
  );

  if (isHero) {
    return (
      <FullBleedLayout bg={props.backgroundColor}>
        <div style={{
          position: "absolute", inset: 0,
          display: "flex", flexDirection: "column",
          justifyContent: "center", alignItems: "center",
          padding: shotPadding,
          overflowY: dataItems.length + textItems.length > 2 ? "auto" : "hidden",
        }}>
          {overlayEls}
          {content}
        </div>
      </FullBleedLayout>
    );
  }

  return (
    <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
      <div style={{
        position: "absolute", inset: 0, padding: shotPadding,
        display: "flex", flexDirection: "column", justifyContent: "center",
        overflowY: dataItems.length + textItems.length > 2 ? "auto" : "hidden",
      }}>
        {overlayEls}
        {content}
      </div>
    </PaddedLayout>
  );
};

// ── In-scene shot progress bar (data-driven; no global timing dependency) ──
const ShotProgressBar = ({ props, shots, totalFrames }) => {
  const frame = useCurrentFrame();
  const progress = totalFrames > 0 ? frame / totalFrames : 0;
  return (
    <div style={{
      position: "absolute", bottom: 0, left: 0, right: 0,
      height: props.progressBarHeight, background: "#fff",
      borderTop: "2px solid #e5e7eb", display: "flex", alignItems: "center",
      padding: "0 60px", gap: 20,
      fontFamily: "PingFang SC, Microsoft YaHei, sans-serif",
    }}>
      {(shots || []).map((ch) => {
        const chStart = totalFrames > 0 ? ch.start_frame / totalFrames : 0;
        const chEnd = totalFrames > 0
          ? (ch.start_frame + ch.duration_frames) / totalFrames : 0;
        const isActive = progress >= chStart && progress < chEnd;
        const isPast = progress >= chEnd;
        const chProgress = isActive
          ? (progress - chStart) / (chEnd - chStart)
          : isPast ? 1 : 0;
        return (
          <div key={ch.name} style={{
            flex: ch.duration_frames, height: 76, borderRadius: 38,
            position: "relative", overflow: "hidden",
            background: isActive ? props.progressActiveColor : isPast ? "#f3f4f6" : "#f9fafb",
            border: isActive ? "none" : "2px solid #e5e7eb",
            display: "flex", alignItems: "center", justifyContent: "center",
          }}>
            {isActive && (
              <div style={{
                position: "absolute", left: 0, top: 0, bottom: 0,
                width: `${chProgress * 100}%`, background: "rgba(255,255,255,0.25)",
                borderRadius: 38,
              }} />
            )}
            <span style={{
              position: "relative", zIndex: 1,
              color: isActive ? "#fff" : isPast ? "#374151" : "#9ca3af",
              fontSize: props.progressFontSize, fontWeight: isActive ? 700 : 500,
              whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis",
              padding: "0 20px",
            }}>{ch.label || ch.name}</span>
          </div>
        );
      })}
      <div style={{
        position: "absolute", bottom: 0, left: 0, right: 0, height: 5, background: "#e5e7eb",
      }}>
        <div style={{
          height: "100%", width: `${progress * 100}%`, background: props.progressActiveColor,
        }} />
      </div>
    </div>
  );
};

export const Video = (props) => {
  const timing = useSceneTiming();
  const shots = timing.shots || [];
  const transitionFrames = props.transitionDuration;
  const transitionCount = Math.max(0, shots.length - 1);
  const effectiveTransitionFrames =
    props.transitionType !== "none" && transitionFrames > 0 ? transitionFrames : 0;

  const originalTotal = shots.reduce((sum, s) => sum + (s.duration_frames || 0), 0);
  const targetTotal = timing.total_frames + transitionCount * effectiveTransitionFrames;
  const audioScale = originalTotal > 0 ? targetTotal / originalTotal : 1;

  const compensatedShots = shots.map((s) => ({
    ...s,
    duration_frames: Math.max(15, Math.round((s.duration_frames || 0) * audioScale)),
  }));

  const scaledTotal = compensatedShots.reduce((sum, s) => sum + s.duration_frames, 0);
  const diff = targetTotal - scaledTotal;
  if (compensatedShots.length > 0) {
    const last = compensatedShots[compensatedShots.length - 1];
    last.duration_frames = Math.max(15, last.duration_frames + diff);
  }

  // Load shot designs from composition.json (staticFile).
  const [designShots, setDesignShots] = React.useState([]);
  React.useEffect(() => {
    fetch(staticFile(`scenes/${SCENE}/composition.json`))
      .then((r) => r.json())
      .then((data) => setDesignShots(data.shots || []))
      .catch(() => setDesignShots([]));
  }, []);

  const shotByName = React.useMemo(() => {
    const m = {};
    for (const s of designShots) m[s.name] = s;
    return m;
  }, [designShots]);

  return (
    <AbsoluteFill style={{ backgroundColor: props.backgroundColor }}>
      <Scale4K orientation={props.orientation} scaleFactor={props.scaleFactor}>
        <TransitionSeries>
          {compensatedShots.map((shot, i) => {
            const design = shotByName[shot.name] || {};
            const merged = { ...shot, ...design };
            return (
              <React.Fragment key={shot.name + i}>
                <TransitionSeries.Sequence durationInFrames={shot.duration_frames}>
                  <ShotComponent shot={merged} props={props} />
                </TransitionSeries.Sequence>
                {i < shots.length - 1 && effectiveTransitionFrames > 0 && (
                  <TransitionSeries.Transition
                    presentation={getPresentation(props.transitionType)}
                    timing={linearTiming({ durationInFrames: transitionFrames })}
                  />
                )}
              </React.Fragment>
            );
          })}
        </TransitionSeries>
      </Scale4K>

      {props.showProgressBar && (
        <ShotProgressBar props={props} shots={timing.shots} totalFrames={timing.total_frames} />
      )}

      {props.enableSubtitles && (
        <Subtitles
          src={staticFile(`scenes/${SCENE}/narration.srt`)}
          fontSize={props.scaleFactor * 40}
          bgBorderRadius={props.scaleFactor * 8}
          bottomOffset={props.scaleFactor * 28}
        />
      )}

      {props.enableAudio && (
        <Audio src={staticFile(`scenes/${SCENE}/narration.wav`)} />
      )}
    </AbsoluteFill>
  );
};

export default Video;
"""


ENTRY_TSX_TEMPLATE = r"""// AUTO-GENERATED by explainer-video-maker/scripts/compose_video.py
// Remotion entry for scene "__SCENE_NAME__" — mounts <Video> as a Composition.

import { Composition, registerRoot, staticFile } from "remotion";
import { Video } from "./scene.tsx";

const defaultProps = __DEFAULT_PROPS__;

const calculateVideoMetadata = async ({ props }) => {
  const resp = await fetch(staticFile("scenes/__SCENE_NAME__/timing.json"));
  const timing = await resp.json();
  return { durationInFrames: timing.total_frames || 150, props };
};

export const RemotionRoot = () => {
  return (
    <Composition
      id="__COMP_ID__"
      component={Video}
      durationInFrames={300}
      calculateMetadata={calculateVideoMetadata}
      fps={__FPS__}
      width={__WIDTH__}
      height={__HEIGHT__}
      defaultProps={defaultProps}
    />
  );
};

registerRoot(RemotionRoot);
"""


def build_parser():
    parser = argparse.ArgumentParser(description="Generate per-scene Remotion composition files.")
    cli_envelope.add_format_arg(parser)
    parser.add_argument("--project", required=True)
    parser.add_argument("--video", required=True)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    prefs_path = workspace.prefs_path(args.project)
    if not os.path.isfile(prefs_path):
        cli_envelope.emit_usage_error(
            f"Project prefs not found: {prefs_path} "
            f"(projects resolve under the workspace: {workspace.projects_dir()}; "
            "run from the workspace root or set EXPLAINER_WORKSPACE)",
            fmt=args.format)
    with open(prefs_path, "r", encoding="utf-8") as f:
        prefs = yaml.safe_load(f) or {}
    # Deep-merge theme onto prefs.
    category = prefs.get("project", {}).get("category")
    if category:
        theme_data = themes_mod.show_theme(category)
        if theme_data:
            prefs = themes_mod.resolve_theme(category, prefs_path)

    video_dir = workspace.video_dir(args.project, args.video)
    if not os.path.isdir(video_dir):
        cli_envelope.emit_usage_error(
            f"Video dir not found: {video_dir}", fmt=args.format)

    script_path = os.path.join(video_dir, "narration_script.yaml")
    try:
        script = script_schema.load_script(script_path)
    except script_schema.SchemaError as exc:
        cli_envelope.emit_usage_error(str(exc), fmt=args.format)

    template_abs = _template_path(prefs).replace("\\", "/")
    default_props_json = json.dumps(_default_props(prefs), ensure_ascii=False, indent=2)
    comp_id = _composition_id(prefs)
    fps = str(prefs.get("video", {}).get("fps", 30))
    width, height = _composition_dims(prefs)

    generated = []
    for scene in script["scenes"]:
        name = scene["name"]
        scene_dir = os.path.join(video_dir, "scenes", name)
        os.makedirs(scene_dir, exist_ok=True)

        # composition.json — shot designs for runtime staticFile consumption.
        composition = {
            "scene": {
                "name": name,
                "label": scene.get("label") or name,
                "chapter": scene.get("chapter"),
            },
            "shots": script_schema.effective_shots(scene),
        }
        composition_path = os.path.join(scene_dir, "composition.json")
        with open(composition_path, "w", encoding="utf-8") as f:
            json.dump(composition, f, ensure_ascii=False, indent=2)

        scene_tsx = (SCENE_TSX_TEMPLATE
                     .replace("__TEMPLATE_PATH__", template_abs)
                     .replace("__SCENE_NAME__", name))
        entry_tsx = (ENTRY_TSX_TEMPLATE
                     .replace("__TEMPLATE_PATH__", template_abs)
                     .replace("__SCENE_NAME__", name)
                     .replace("__COMP_ID__", comp_id)
                     .replace("__FPS__", fps)
                     .replace("__WIDTH__", str(width))
                     .replace("__HEIGHT__", str(height))
                     .replace("__DEFAULT_PROPS__", default_props_json))

        scene_tsx_path = os.path.join(scene_dir, "scene.tsx")
        entry_tsx_path = os.path.join(scene_dir, "entry.tsx")
        with open(scene_tsx_path, "w", encoding="utf-8") as f:
            f.write(scene_tsx)
        with open(entry_tsx_path, "w", encoding="utf-8") as f:
            f.write(entry_tsx)

        generated.append({
            "scene": name,
            "scene_tsx": scene_tsx_path,
            "entry_tsx": entry_tsx_path,
            "composition_json": composition_path,
            "shots": [s["name"] for s in composition["shots"]],
        })

    cli_envelope.emit_ok(
        data={
            "scenes": generated,
            "composition_id": comp_id,
            "dimensions": [width, height],
            "default_props": _default_props(prefs),
            "render_hint": (
                'cd "$TEMPLATE_PATH" && npx remotion render '
                '"$VDIR/scenes/<scene>/entry.tsx" '
                f'{comp_id} "$VDIR/scenes/<scene>/scene.mp4" '
                '--public-dir "$VDIR" --video-bitrate 16M'
            ),
        },
        message=f"Generated scene.tsx + entry.tsx for {len(generated)} scene(s).",
        fmt=args.format,
    )


if __name__ == "__main__":
    main()
