#!/usr/bin/env python3
"""Generate per-video Remotion composition files.

Produces two files in the video directory:
    Video.tsx — a SectionComponent switch driven by section.component,
                importing components from the shared remotion-video-template.
    entry.tsx — a Composition registration mounting <Video> with project prefs.

Also writes `narration_script.json` (a JSON mirror of narration_script.yaml)
so the composition can read per-section props at runtime via staticFile.

Strategy:
    The generated Video.tsx mirrors the audio-master-clock math from the
    template's src/Video.js (TransitionSeries overlap compensation). The
    SectionComponent switch reads `section.component` (from the script) and
    composes one of the template's exported components.
"""
import argparse
import json
import os
import sys

import yaml

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
SKILL_DIR = os.path.dirname(SCRIPT_DIR)
DOC_ROOT = os.path.normpath(os.path.join(SKILL_DIR, "..", ".."))
sys.path.insert(0, SCRIPT_DIR)
import cli_envelope  # noqa: E402
import themes as themes_mod  # noqa: E402


def _template_path(prefs):
    rel = prefs.get("paths", {}).get("remotion_template", "../../remotion-video-template")
    return os.path.normpath(os.path.join(SKILL_DIR, rel))


def _composition_id(prefs):
    orientation = prefs.get("project", {}).get("orientation", "horizontal")
    resolution = prefs.get("video", {}).get("resolution", "1080p")
    if orientation == "vertical":
        return "MainVideoVertical"
    if resolution == "4k":
        return "MainVideo4K"
    return "MainVideo"


def _composition_dims(prefs):
    orientation = prefs.get("project", {}).get("orientation", "horizontal")
    resolution = prefs.get("video", {}).get("resolution", "1080p")
    if orientation == "vertical":
        return (1080, 1920)
    if resolution == "4k":
        return (3840, 2160)
    return (1920, 1080)


def _default_props(prefs):
    theme = prefs.get("theme", {})
    return {
        "primaryColor": theme.get("primary_color", "#1a2a3a"),
        "backgroundColor": theme.get("background_color", "#0e1419"),
        "textColor": theme.get("text_color", "#e6e8eb"),
        "accentColor": theme.get("accent_color", "#d4b483"),
        "titleSize": 80,
        "subtitleSize": 40,
        "bodySize": 28,
        "showProgressBar": True,
        "progressBarHeight": 65,
        "progressFontSize": 19,
        "progressActiveColor": theme.get("primary_color", "#1a2a3a"),
        "bgmVolume": 0,
        "enableAudio": True,
        "enableSubtitles": False,
        "enableAnimations": True,
        "transitionType": theme.get("transition_type", "fade"),
        "transitionDuration": theme.get("transition_duration", 18),
        "scaleFactor": 2 if prefs.get("video", {}).get("resolution") == "4k" else 1,
        "orientation": prefs.get("project", {}).get("orientation", "horizontal"),
        "iconStyle": "lucide",
        "iconAnimation": "entrance",
    }


VIDEO_TSX_TEMPLATE = r"""// AUTO-GENERATED by explainer-video-maker/scripts/compose_video.py
// Per-video composition. Imports components from the shared remotion-video-template.
//
// Audio-master clock: TransitionSeries renders sum(sections) - (N-1)*overlap.
// Every section is scaled proportionally so the rendered total equals
// timing.total_frames. Overlap math mirrors remotion-video-template/src/Video.js.

import React from "react";
import { Audio, staticFile, AbsoluteFill } from "remotion";
import { TransitionSeries, linearTiming } from "@remotion/transitions";

import {
  Scale4K, FullBleedLayout, PaddedLayout,
  useEntrance, getPresentation,
  ChapterProgressBar, Subtitles,
  AssetImage, AssetVideo, MediaSection,
  Timeline, FlowChart, DataBar, QuoteBlock,
  StatHighlight, SplitLayout, ComparisonCard,
  DiagramReveal, MetricsRow, StepProgress,
  IconCard, Icon, FeatureGrid,
  MovingGradient, FloatingShapes, GlowOrb,
  useTiming,
} from "__TEMPLATE_PATH__/src/components/index.js";

const SectionComponent = ({ section, props }) => {
  const { opacity, translateY, scale } = useEntrance(props.enableAnimations);
  const animStyle = {
    opacity,
    transform: `translateY(${translateY}px) scale(${scale})`,
  };
  const v = props.orientation === "vertical";
  const sectionPadding = v ? "120px 60px 160px" : "60px 100px 120px";
  const visual = section.visual || {};
  const component = visual.component || section.component;
  const vp = visual.props || {};
  const assetId = visual.asset_id;

  switch (component) {
    case "FullBleedLayout":
    case "hero":
      return (
        <FullBleedLayout bg={props.backgroundColor}>
          {assetId ? (
            <AssetImage props={props} id={assetId} role="background" />
          ) : (
            <MovingGradient color1={props.primaryColor} color2={props.accentColor} />
          )}
          <div style={{
            position: "absolute", inset: 0,
            display: "flex", flexDirection: "column",
            justifyContent: "center", alignItems: "center",
            textAlign: "center", padding: v ? "0 60px" : 0,
            ...animStyle,
          }}>
            <h1 style={{
              fontSize: props.titleSize, fontWeight: 800,
              color: props.primaryColor, lineHeight: v ? 1.3 : 1.1,
            }}>{vp.title || section.label || section.name}</h1>
            {vp.subtitle && (
              <p style={{
                fontSize: props.subtitleSize, color: props.textColor,
                marginTop: v ? 32 : 20, opacity: 0.6, fontWeight: 500,
              }}>{vp.subtitle}</p>
            )}
          </div>
        </FullBleedLayout>
      );

    case "Timeline":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
              marginBottom: v ? 32 : 40,
            }}>{vp.title || section.label}</h2>
            <Timeline props={props} items={vp.items || []} />
          </div>
        </PaddedLayout>
      );

    case "FlowChart":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
              marginBottom: v ? 32 : 40,
            }}>{vp.title || section.label}</h2>
            <FlowChart props={props} steps={vp.steps || []} />
          </div>
        </PaddedLayout>
      );

    case "DiagramReveal":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
              marginBottom: v ? 32 : 40,
            }}>{vp.title || section.label}</h2>
            <DiagramReveal props={props}
              nodes={vp.nodes || []} edges={vp.edges || []} />
          </div>
        </PaddedLayout>
      );

    case "DataBar":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
              marginBottom: v ? 32 : 40,
            }}>{vp.title || section.label}</h2>
            <DataBar props={props} items={vp.items || []} />
          </div>
        </PaddedLayout>
      );

    case "MetricsRow":
      return (
        <MetricsRow props={props}
          title={vp.title || section.label}
          metrics={vp.metrics || []} />
      );

    case "StepProgress":
      return (
        <StepProgress props={props}
          title={vp.title || section.label}
          steps={vp.steps || []} />
      );

    case "QuoteBlock":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", alignItems: "center", justifyContent: "center",
            ...animStyle,
          }}>
            <QuoteBlock props={props}
              quote={vp.quote || ""}
              attribution={vp.attribution || ""} />
          </div>
        </PaddedLayout>
      );

    case "SplitLayout":
      return (
        <SplitLayout props={props}
          title={vp.title || section.label}
          description={vp.description || ""}
          rightContent={vp.rightContent || null} />
      );

    case "ComparisonCard":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
              marginBottom: v ? 32 : 40,
            }}>{vp.title || section.label}</h2>
            <ComparisonCard props={props}
              left={vp.left || { title: "", items: [] }}
              right={vp.right || { title: "", items: [] }} />
          </div>
        </PaddedLayout>
      );

    case "StatHighlight":
      return (
        <StatHighlight props={props}
          value={vp.value || ""} unit={vp.unit || ""}
          label={vp.label || section.label}
          description={vp.description || ""} />
      );

    case "MediaSection":
    case "AssetImage":
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            maxWidth: 1100, margin: "0 auto",
            ...animStyle,
          }}>
            {assetId ? (
              <AssetImage props={props} id={assetId} role="inline"
                caption={vp.caption} layout={vp.layout || "full"} />
            ) : (
              <p style={{ fontSize: 28, textAlign: "center" }}>
                MediaSection requires an asset_id.
              </p>
            )}
          </div>
        </PaddedLayout>
      );

    case "AssetVideo":
      return assetId ? (
        <AbsoluteFill>
          <AssetVideo props={props} id={assetId} />
        </AbsoluteFill>
      ) : null;

    default:
      return (
        <PaddedLayout bg={props.backgroundColor} orientation={props.orientation}>
          <div style={{
            position: "absolute", inset: 0, padding: sectionPadding,
            display: "flex", flexDirection: "column", justifyContent: "center",
            ...animStyle,
          }}>
            <h2 style={{
              fontSize: v ? 72 : 80, fontWeight: 700,
              color: props.primaryColor, textAlign: "center",
            }}>{section.label || section.name}</h2>
          </div>
        </PaddedLayout>
      );
  }
};

export const Video = (props) => {
  const timing = useTiming();
  const sections = timing.sections;
  const transitionFrames = props.transitionDuration;
  const transitionCount = Math.max(0, sections.length - 1);
  const effectiveTransitionFrames =
    props.transitionType !== "none" && transitionFrames > 0 ? transitionFrames : 0;

  const originalTotal = sections.reduce((sum, s) => sum + (s.duration_frames || 0), 0);
  const targetTotal = timing.total_frames + transitionCount * effectiveTransitionFrames;
  const audioScale = originalTotal > 0 ? targetTotal / originalTotal : 1;

  const compensatedSections = sections.map((s) => ({
    ...s,
    duration_frames: Math.max(15, Math.round((s.duration_frames || 0) * audioScale)),
  }));

  const scaledTotal = compensatedSections.reduce((sum, s) => sum + s.duration_frames, 0);
  const diff = targetTotal - scaledTotal;
  if (compensatedSections.length > 0) {
    const last = compensatedSections[compensatedSections.length - 1];
    last.duration_frames = Math.max(15, last.duration_frames + diff);
  }

  // Load per-section visual design from narration_script.json (staticFile).
  const [scriptSections, setScriptSections] = React.useState([]);
  React.useEffect(() => {
    fetch(staticFile("narration_script.json"))
      .then((r) => r.json())
      .then((data) => setScriptSections(data.sections || data || []))
      .catch(() => setScriptSections([]));
  }, []);

  const sectionByName = React.useMemo(() => {
    const m = {};
    for (const s of scriptSections) m[s.name] = s;
    return m;
  }, [scriptSections]);

  return (
    <AbsoluteFill style={{ backgroundColor: props.backgroundColor }}>
      <Scale4K orientation={props.orientation} scaleFactor={props.scaleFactor}>
        <TransitionSeries>
          {compensatedSections.map((section, i) => {
            const scriptSection = sectionByName[section.name] || {};
            const merged = { ...section, ...scriptSection };
            return (
              <React.Fragment key={section.name + i}>
                <TransitionSeries.Sequence durationInFrames={section.duration_frames}>
                  <SectionComponent section={merged} props={props} />
                </TransitionSeries.Sequence>
                {i < sections.length - 1 && transitionFrames > 0 && props.transitionType !== "none" && (
                  <TransitionSeries.Transition
                    presentation={getPresentation(props.transitionType)}
                    timing={linearTiming({ durationInFrames: transitionFrames })}
                  />
                )}
              </React.Fragment>
            );
          })}
        </TransitionSeries>
      </Scale4K>

      <ChapterProgressBar props={props} chapters={timing.sections} />

      {props.enableSubtitles && (
        <Subtitles
          src={staticFile("narration_audio.srt")}
          fontSize={props.scaleFactor * 40}
          bgBorderRadius={props.scaleFactor * 8}
          bottomOffset={props.scaleFactor * 28}
        />
      )}

      {props.bgmVolume > 0 && (
        <Audio src={staticFile("bgm.mp3")} volume={props.bgmVolume} />
      )}

      {props.enableAudio && (
        <Audio src={staticFile("narration_audio.wav")} />
      )}
    </AbsoluteFill>
  );
};

export default Video;
"""


ENTRY_TSX_TEMPLATE = r"""// AUTO-GENERATED by explainer-video-maker/scripts/compose_video.py
// Remotion entry — mounts the per-video <Video> component as a Composition.

import { Composition } from "remotion";
import { Video } from "./Video.js";
import { fetchTimingData } from "__TEMPLATE_PATH__/src/components/index.js";

const defaultProps = __DEFAULT_PROPS__;

const calculateVideoMetadata = async ({ props }) => {
  const timing = await fetchTimingData();
  return { durationInFrames: timing.total_frames || 300, props };
};

export const RemotionRoot = () => {
  return (
    <Composition
      id="__COMP_ID__"
      component={Video}
      durationInFrames={300}
      calculateMetadata={calculateVideoMetadata}
      fps={__FPS__}
      width={__WIDTH__}
      height={__HEIGHT__}
      defaultProps={defaultProps}
    />
  );
};
"""


def build_parser():
    parser = argparse.ArgumentParser(description="Generate per-video Remotion composition files.")
    cli_envelope.add_format_arg(parser)
    parser.add_argument("--project", required=True)
    parser.add_argument("--video", required=True)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    prefs_path = os.path.join(DOC_ROOT, "projects", args.project, "project_prefs.yaml")
    if not os.path.isfile(prefs_path):
        cli_envelope.emit_usage_error(
            f"Project prefs not found: {prefs_path}", fmt=args.format)
    with open(prefs_path, "r", encoding="utf-8") as f:
        prefs = yaml.safe_load(f) or {}
    # Deep-merge theme onto prefs.
    category = prefs.get("project", {}).get("category")
    if category:
        theme_data = themes_mod.show_theme(category)
        if theme_data:
            prefs = themes_mod.resolve_theme(category, prefs_path)

    video_dir = os.path.join(DOC_ROOT, "projects", args.project, "videos", args.video)
    if not os.path.isdir(video_dir):
        cli_envelope.emit_usage_error(
            f"Video dir not found: {video_dir}", fmt=args.format)

    # Write narration_script.json (JSON mirror for staticFile consumption).
    script_path = os.path.join(video_dir, "narration_script.yaml")
    if not os.path.isfile(script_path):
        cli_envelope.emit_usage_error(
            f"narration_script.yaml not found at {script_path}", fmt=args.format)
    with open(script_path, "r", encoding="utf-8") as f:
        script_sections = yaml.safe_load(f) or []
    with open(os.path.join(video_dir, "narration_script.json"), "w", encoding="utf-8") as f:
        json.dump({"sections": script_sections}, f, ensure_ascii=False, indent=2)

    template_abs = _template_path(prefs).replace("\\", "/")
    video_tsx = VIDEO_TSX_TEMPLATE.replace("__TEMPLATE_PATH__", template_abs)
    entry_tsx = (ENTRY_TSX_TEMPLATE
                 .replace("__TEMPLATE_PATH__", template_abs)
                 .replace("__COMP_ID__", _composition_id(prefs))
                 .replace("__FPS__", str(prefs.get("video", {}).get("fps", 30)))
                 .replace("__WIDTH__", str(_composition_dims(prefs)[0]))
                 .replace("__HEIGHT__", str(_composition_dims(prefs)[1]))
                 .replace("__DEFAULT_PROPS__", json.dumps(_default_props(prefs), ensure_ascii=False, indent=2)))

    video_tsx_path = os.path.join(video_dir, "Video.tsx")
    entry_tsx_path = os.path.join(video_dir, "entry.tsx")
    with open(video_tsx_path, "w", encoding="utf-8") as f:
        f.write(video_tsx)
    with open(entry_tsx_path, "w", encoding="utf-8") as f:
        f.write(entry_tsx)

    cli_envelope.emit_ok(
        data={
            "video_tsx": video_tsx_path,
            "entry_tsx": entry_tsx_path,
            "composition_id": _composition_id(prefs),
            "dimensions": _composition_dims(prefs),
            "default_props": _default_props(prefs),
        },
        message=f"Generated Video.tsx + entry.tsx for '{args.video}'.",
        fmt=args.format,
    )


if __name__ == "__main__":
    main()
